[project]
name = "yaml-to-schemdraw"
version = "0.1.2"
description = "Generate schemdraw diagrams from YAML files or Python dictionaries."
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["ruamel-yaml", "schemdraw"]

[project.urls]
Homepage = "https://github.com/Julynx/yaml-to-schemdraw"
Repository = "https://github.com/Julynx/yaml-to-schemdraw"

[dependency-groups]
dev = ["pylint", "pytest"]
